trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 
    displayName: Build
    jobs:
    - job: build
      steps:
        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/web-app.zip'
            replaceExistingArchive: true

        - publish: $(Build.ArtifactStagingDirectory)
          artifact: web-app 

  - stage: 
    displayName: Deploy DEV
    jobs:
    - deployment: DEV
      displayName: Deploy to Web App
      environment: DEV
      strategy: 
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: web-app

              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'DevopsProjectService'  # Ensure this matches your service connection name
                  appType: 'webApp'
                  WebAppName: 'RGATES5626259-Prod'
                  packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
                  enableCustomDeployment: true
                  DeploymentType: 'webDeploy'

  - stage: 
    displayName: Deploy TEST
    jobs:
    - deployment: TEST
      displayName: Deploy to Web App
      environment: TEST
      strategy: 
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: web-app

              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'DevopsProjectService'  # Ensure this matches your service connection name
                  appType: 'webApp'
                  WebAppName: 'RGATES5626259-Prod'
                  packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
                  enableCustomDeployment: true
                  DeploymentType: 'webDeploy'
