trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker'
        repository: 'userisabdullah/devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: Terraform
  displayName: 'Terraform Deployment'
  jobs:
  - job: Terraform
    displayName: 'Terraform Operations'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        # Install Terraform
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

        # Execute Terraform commands
        cd $(System.DefaultWorkingDirectory)
        terraform init
        terraform validate
        terraform plan
        terraform apply -auto-approve
      displayName: 'Install Terraform and Execute Commands'
